use anyhow::{Context, Result, bail};
use std::env;
use std::fs;
use std::os::unix::fs::{PermissionsExt, symlink};
use std::path::{Path, PathBuf};
use toml_edit::{DocumentMut, value};

const PRIVATE_ENTRIES: &[&str] = &[
    "config.toml",
    "app-server-control",
    "app-server-daemon",
    "ipc",
    "log",
    "logs",
    "process_manager",
    "tmp",
    ".tmp",
];

pub fn managed_codex_home(root: &Path) -> PathBuf {
    root.join("codex-home")
}

pub fn prepare_managed_home(
    os_home: &Path,
    real_codex_home: &Path,
    managed_root: &Path,
    personal_marketplace: &Path,
    bundled_marketplace: &Path,
) -> Result<PathBuf> {
    let managed_home = managed_codex_home(managed_root);
    fs::create_dir_all(&managed_home)
        .with_context(|| format!("failed to create {}", managed_home.display()))?;
    fs::set_permissions(&managed_home, fs::Permissions::from_mode(0o700))?;

    link_shared_entries(real_codex_home, &managed_home)?;
    write_sanitized_config(
        os_home,
        real_codex_home,
        &managed_home,
        personal_marketplace,
        bundled_marketplace,
    )?;
    Ok(managed_home)
}

fn link_shared_entries(real_home: &Path, managed_home: &Path) -> Result<()> {
    if !real_home.is_dir() {
        bail!("real CODEX_HOME is unavailable at {}", real_home.display());
    }
    for entry in fs::read_dir(real_home)? {
        let entry = entry?;
        let name = entry.file_name();
        let name_text = name.to_string_lossy();
        if is_private_entry(&name_text) {
            let existing = managed_home.join(&name);
            if fs::symlink_metadata(&existing).is_ok_and(|m| m.file_type().is_symlink()) {
                fs::remove_file(existing)?;
            }
            continue;
        }
        let source = entry.path();
        let destination = managed_home.join(&name);
        match fs::symlink_metadata(&destination) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                if fs::read_link(&destination)? == source {
                    continue;
                }
                fs::remove_file(&destination)?;
            }
            Ok(_) => bail!(
                "managed CODEX_HOME contains an unmanaged entry at {}",
                destination.display()
            ),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(error.into()),
        }
        symlink(&source, &destination).with_context(|| {
            format!(
                "failed to link shared CODEX_HOME entry {}",
                destination.display()
            )
        })?;
    }
    Ok(())
}

fn is_private_entry(name: &str) -> bool {
    PRIVATE_ENTRIES.contains(&name)
        || name.starts_with("state_")
        || name.starts_with("state.")
        || name.ends_with(".sqlite")
        || name.ends_with(".sqlite-wal")
        || name.ends_with(".sqlite-shm")
        || name.starts_with("..codex-global-state.json.tmp-")
}

fn write_sanitized_config(
    os_home: &Path,
    real_home: &Path,
    managed_home: &Path,
    marketplace: &Path,
    bundled_marketplace: &Path,
) -> Result<()> {
    let source = real_home.join("config.toml");
    let text = fs::read_to_string(&source)
        .with_context(|| format!("failed to read {}", source.display()))?;
    let mut document = text
        .parse::<DocumentMut>()
        .with_context(|| format!("failed to parse {}", source.display()))?;

    inject_unified_computer_use(&mut document, bundled_marketplace, real_home, os_home)?;
    let os_home = os_home.to_str().context("HOME path is not valid UTF-8")?;
    if let Some(projects) = document
        .get_mut("projects")
        .and_then(toml_edit::Item::as_table_mut)
    {
        projects.remove(os_home);
    }
    if let Some(mcp_servers) = document
        .get_mut("mcp_servers")
        .and_then(toml_edit::Item::as_table_mut)
    {
        // These two entries are generated by older Desktop builds. They launch
        // a bare node_repl (or explicitly disable the legacy client) and mask
        // the current unified-computer-use plugin's own cua_repl definition.
        mcp_servers.remove("node_repl");
        mcp_servers.remove("computer-use");
    }
    let marketplace = marketplace
        .to_str()
        .context("managed marketplace path is not valid UTF-8")?;
    document["marketplaces"]["personal"]["source"] = value(marketplace);
    let bundled_marketplace = bundled_marketplace
        .to_str()
        .context("managed bundled marketplace path is not valid UTF-8")?;
    document["marketplaces"]["openai-bundled"]["source"] = value(bundled_marketplace);
    let real_home = real_home
        .to_str()
        .context("real CODEX_HOME path is not valid UTF-8")?;
    document["sqlite_home"] = value(real_home);

    let destination = managed_home.join("config.toml");
    let temporary = managed_home.join(format!(".config.toml.{}.tmp", std::process::id()));
    fs::write(&temporary, document.to_string())?;
    fs::set_permissions(&temporary, fs::Permissions::from_mode(0o600))?;
    fs::rename(&temporary, &destination)?;
    Ok(())
}

fn inject_unified_computer_use(
    document: &mut DocumentMut,
    marketplace: &Path,
    real_home: &Path,
    os_home: &Path,
) -> Result<()> {
    let config_path = marketplace.join("plugins/unified-computer-use/.mcp.json");
    let config: serde_json::Value = serde_json::from_slice(
        &fs::read(&config_path)
            .with_context(|| format!("failed to read {}", config_path.display()))?,
    )
    .with_context(|| format!("failed to parse {}", config_path.display()))?;
    let mut server = config
        .pointer("/mcpServers/cua_repl")
        .context("unified-computer-use has no cua_repl MCP definition")?
        .clone();
    let server_object = server
        .as_object_mut()
        .context("unified-computer-use cua_repl definition is not an object")?;
    let plugin_root = config_path
        .parent()
        .context("unified-computer-use config has no plugin root")?;
    let desktop_resources = resolve_desktop_resources(os_home)?;
    if server_object
        .get("command")
        .and_then(serde_json::Value::as_str)
        == Some("node")
    {
        server_object.insert(
            "command".into(),
            serde_json::Value::String(
                desktop_resources
                    .join("cua_node/bin/node")
                    .to_string_lossy()
                    .into_owned(),
            ),
        );
    }
    if let Some(arguments) = server_object
        .get_mut("args")
        .and_then(serde_json::Value::as_array_mut)
    {
        for argument in arguments {
            let Some(relative) = argument.as_str() else {
                continue;
            };
            let path = Path::new(relative);
            if !path.is_absolute() {
                *argument = serde_json::Value::String(
                    plugin_root.join(path).to_string_lossy().into_owned(),
                );
            }
        }
    }
    server_object.insert("enabled".into(), serde_json::Value::Bool(true));
    let environment = server_object
        .entry("env")
        .or_insert_with(|| serde_json::Value::Object(serde_json::Map::new()))
        .as_object_mut()
        .context("unified-computer-use cua_repl env is not an object")?;
    environment.insert(
        "CUA_REPL_NODE_REPL_PATH".into(),
        serde_json::Value::String(
            desktop_resources
                .join("cua_node/bin/node_repl")
                .to_string_lossy()
                .into_owned(),
        ),
    );
    let installed_sky = real_home.join("computer-use/Codex Computer Use.app");
    let sky_service = if installed_sky.is_dir() {
        installed_sky
    } else {
        desktop_resources.join("cua_node/lib/node_modules/@oai/sky/Codex Computer Use.app")
    };
    if !sky_service.is_dir() {
        bail!("Codex Computer Use service is unavailable");
    }
    environment.insert(
        "SKY_CUA_SERVICE_PATH".into(),
        serde_json::Value::String(sky_service.to_string_lossy().into_owned()),
    );
    environment.insert(
        "NODE_REPL_HOST_SERVICES_PIPE_PATH".into(),
        serde_json::Value::String(String::new()),
    );
    environment.insert(
        "NODE_REPL_NODE_MODULE_DIRS".into(),
        serde_json::Value::String(
            desktop_resources
                .join("cua_node/lib/node_modules")
                .to_string_lossy()
                .into_owned(),
        ),
    );
    environment.insert(
        "NODE_REPL_TRUSTED_CODE_PATHS".into(),
        serde_json::Value::String(format!(
            "{}:{}",
            real_home.to_string_lossy(),
            desktop_resources
                .join("cua_node/lib/node_modules")
                .to_string_lossy()
        )),
    );
    environment.insert(
        "CUA_REPL_ENABLED_SURFACES".into(),
        serde_json::Value::String("browser,computer".into()),
    );
    environment.insert(
        "CODEX_CLI_PATH".into(),
        serde_json::Value::String(
            desktop_resources
                .join("codex")
                .to_string_lossy()
                .into_owned(),
        ),
    );
    environment.insert(
        "CODEX_HOME".into(),
        serde_json::Value::String(real_home.to_string_lossy().into_owned()),
    );
    let imported = toml_edit::ser::to_document(&serde_json::json!({
        "mcp_servers": {"cua_repl": server}
    }))?;
    document["mcp_servers"]["cua_repl"] = imported["mcp_servers"]["cua_repl"].clone();
    Ok(())
}

fn resolve_desktop_resources(os_home: &Path) -> Result<PathBuf> {
    let candidates = if let Some(override_path) = env::var_os("CODEX_MANAGED_DESKTOP_RESOURCES") {
        vec![PathBuf::from(override_path)]
    } else {
        vec![
            PathBuf::from("/Applications/ChatGPT.app/Contents/Resources"),
            os_home.join("Applications/ChatGPT.app/Contents/Resources"),
        ]
    };

    for candidate in candidates {
        let required_files = [
            candidate.join("codex"),
            candidate.join("cua_node/bin/node"),
            candidate.join("cua_node/bin/node_repl"),
        ];
        let node_modules = candidate.join("cua_node/lib/node_modules");
        if required_files.iter().all(|path| path.is_file()) && node_modules.is_dir() {
            return fs::canonicalize(&candidate)
                .with_context(|| format!("cannot resolve {}", candidate.display()));
        }
    }

    bail!(
        "supported ChatGPT Desktop resources are unavailable; set CODEX_MANAGED_DESKTOP_RESOURCES"
    )
}
